// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  blocks: create.doc("blocks", {"patient-registration-form.mdx": () => import("../content/blocks/patient-registration-form.mdx?collection=blocks"), }),
  docs: create.doc("docs", {"fhir-address-input.mdx": () => import("../content/docs/fhir-address-input.mdx?collection=docs"), "fhir-attachment-input.mdx": () => import("../content/docs/fhir-attachment-input.mdx?collection=docs"), "fhir-birth-place-input.mdx": () => import("../content/docs/fhir-birth-place-input.mdx?collection=docs"), "fhir-citizenship-status-input.mdx": () => import("../content/docs/fhir-citizenship-status-input.mdx?collection=docs"), "fhir-codeable-concept-input.mdx": () => import("../content/docs/fhir-codeable-concept-input.mdx?collection=docs"), "fhir-contact-point-input.mdx": () => import("../content/docs/fhir-contact-point-input.mdx?collection=docs"), "fhir-country-selector.mdx": () => import("../content/docs/fhir-country-selector.mdx?collection=docs"), "fhir-date-input.mdx": () => import("../content/docs/fhir-date-input.mdx?collection=docs"), "fhir-datetime-input.mdx": () => import("../content/docs/fhir-datetime-input.mdx?collection=docs"), "fhir-dosage-input.mdx": () => import("../content/docs/fhir-dosage-input.mdx?collection=docs"), "fhir-gender-input.mdx": () => import("../content/docs/fhir-gender-input.mdx?collection=docs"), "fhir-human-name-input.mdx": () => import("../content/docs/fhir-human-name-input.mdx?collection=docs"), "fhir-identifier-input.mdx": () => import("../content/docs/fhir-identifier-input.mdx?collection=docs"), "fhir-location-input.mdx": () => import("../content/docs/fhir-location-input.mdx?collection=docs"), "fhir-marital-status-input.mdx": () => import("../content/docs/fhir-marital-status-input.mdx?collection=docs"), "fhir-money-input.mdx": () => import("../content/docs/fhir-money-input.mdx?collection=docs"), "fhir-odontogram-input.mdx": () => import("../content/docs/fhir-odontogram-input.mdx?collection=docs"), "fhir-organization-input.mdx": () => import("../content/docs/fhir-organization-input.mdx?collection=docs"), "fhir-period-input.mdx": () => import("../content/docs/fhir-period-input.mdx?collection=docs"), "fhir-practitioner-input.mdx": () => import("../content/docs/fhir-practitioner-input.mdx?collection=docs"), "fhir-quantity-input.mdx": () => import("../content/docs/fhir-quantity-input.mdx?collection=docs"), "fhir-reference-input.mdx": () => import("../content/docs/fhir-reference-input.mdx?collection=docs"), "fhir-regional-selector.mdx": () => import("../content/docs/fhir-regional-selector.mdx?collection=docs"), "fhir-religion-input.mdx": () => import("../content/docs/fhir-religion-input.mdx?collection=docs"), "fhir-vital-signs-input.mdx": () => import("../content/docs/fhir-vital-signs-input.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), }),
};
export default browserCollections;